# Generated by Django 5.2.5 on 2025-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(help_text='Enter the song title', max_length=200)),
                ('artist', models.CharField(help_text='Enter the artist name', max_length=200)),
                ('album_cover', models.ImageField(blank=True, help_text='Upload album cover image', null=True, upload_to='album_covers/')),
                ('album_cover_url', models.URLField(blank=True, help_text='Or provide URL for album cover', null=True)),
                ('spotify_youtube_url', models.URLField(help_text='Spotify or YouTube embed link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Music List',
                'ordering': ['-created_at'],
            },
        ),
    ]
